/**
 * Sanitation types.
 */
export const enum SanitizeTypes {
  BLACKLIST = 'BLACKLIST',
  ESCAPE = 'ESCAPE',
  LTRIM = 'LTRIM',
  NORMALIZE_EMAIL = 'NORMALIZE_EMAIL',
  RTRIM = 'RTRIM',
  STRIP_LOW = 'STRIP_LOW',
  TO_BOOLEAN = 'TO_BOOLEAN',
  TO_DATE = 'TO_DATE',
  TO_FLOAT = 'TO_FLOAT',
  TO_INT = 'TO_INT',
  TO_STRING = 'TO_STRING',
  TRIM = 'TRIM',
  WHITELIST = 'WHITELIST',
  CUSTOM_SANITIZATION = 'CUSTOM_SANITIZATION',
  NESTED = 'NESTED',
}
